version: "3.8"

services:
  db:
    image: mysql:8.0.30
    container_name: db-yoyakun
    environment:
      MYSQL_DATABASE: yoyakun
      MYSQL_USER: yoyakun
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306

  yoyakun:
    container_name: yoyakun
    build:
      context: ./docker/php
    ports:
      - "80:80"
      - "5173:5173"
    volumes:
      - ./:/var/www/html
      - ./docker/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
